spring:
  application:
    name: command-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_ledger
    username: aastha
    password: aastha
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  data:
    redis:
      host: localhost
      port: 6379
      password: aastha
      timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: >-
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer: >-
        org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

server:
  port: 8081

logging:
  level:
    com.paymentledger: DEBUG
    org.flywaydb: INFO

app:
  kafka:
    topic:
      transfer-events: transfer-events
  reconciliation:
      discrepancy-threshold: 100.00
      cron: "0 0 0 * * *"