spring:
  application:
    name: projection-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_ledger
    username: aastha
    password: aastha
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: projection-service
      auto-offset-reset: earliest
      key-deserializer: >-
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: >-
        org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: >-
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer: >-
        org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    dlq:
      group-id : projection-service-dlq


server:
  port: 8082

logging:
  level:
    com.paymentledger: DEBUG
    org.apache.kafka: WARN

app:
  kafka:
    topic:
        transfer-events: transfer-events
        transfer-events-dlq: transfer-events-dlq
    retry:
      max-attempts: 3
      backoff-delay: 1000
